import Head from 'next/head'
import { PropTypes } from 'prop-types'

export const HeadComponent = (props) => {
  return (
    <Head>
      <meta name='description' content='Generated by create next app' />
      <link rel='icon' href='/favicon.ico' />
      <title>{props.title}</title>
    </Head>
  )
}

HeadComponent.propTypes = {
  title: PropTypes.string,
}
